# Generated by Django 3.2.5 on 2021-07-13 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Primeiro nome')),
                ('sobrenome', models.CharField(max_length=100)),
                ('data_admissao', models.DateField(verbose_name='Data de admissão')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=130)),
                ('endereco', models.CharField(max_length=250, verbose_name='Endereço')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala_app.medicos')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala_app.postos')),
            ],
        ),
        migrations.CreateModel(
            name='Dia_de_Folga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_folga', models.DateField(verbose_name='Dia de folga')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala_app.medicos')),
            ],
        ),
    ]
