# Generated by Django 3.2.5 on 2021-07-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escala_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia_de_folga',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dia_de_folga', to='escala_app.medicos'),
        ),
        migrations.AlterField(
            model_name='postos',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status(para desativar o médico desmarque esta opção):'),
        ),
    ]
