# Generated by Django 3.2.5 on 2021-07-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_app', '0002_auto_20210714_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status(para desativar o médico desmarque esta opção):'),
        ),
        migrations.AlterField(
            model_name='postos',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status(para desativar o posto desmarque esta opção):'),
        ),
    ]
