# Generated by Django 5.1.6 on 2025-03-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escala_app", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
