# Generated by Django 3.2.5 on 2021-07-15 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escala_app', '0003_auto_20210714_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia_de_folga',
            name='dia_folga',
            field=models.DateField(verbose_name='Dia de folga (DD/MM/AAAA)'),
        ),
        migrations.AlterField(
            model_name='dia_de_folga',
            name='medico',
            field=models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, related_name='dia_de_folga', to='escala_app.medicos'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='data',
            field=models.DateField(verbose_name='Dia (DD/MM/AAAA)'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='medico',
            field=models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, related_name='medico', to='escala_app.medicos'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='posto',
            field=models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, related_name='posto', to='escala_app.postos'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='data_admissao',
            field=models.DateField(verbose_name='Data de admissão (DD/MM/AAAA)'),
        ),
    ]
